### ISSUE TITLE
docs: how to show help 大家觉得帮助文档之类的如何给出比较好？

### ISSUE THREAD

**Issue by snomiao** [snolab/CapsLockX#1]

**Comment by snomiao** [comment]
目前是 CLX+/ 键 呼出临时帮助，
然后CLX+Shift+/ 打开Issues，
CLX+Alt+/ 打开CLX主页，
不过这样还是不太直观……
比较理想的方式是键位图（或者像面包导航一样的语法提示？ ），这2种做起来有点复杂就还没来得及研究……

**Comment by moonhuahua** [comment]
最好是按win+F1调出下面例图，重要的是，松开win+F1时，图片自动消失（此功能我常用）
![image](https://user-images.githubusercontent.com/15684037/158143488-f49ce849-d179-4ff5-bbaa-7332166e94d7.png)
