### ISSUE TITLE
帮助里有乱码 caps+/

### ISSUE THREAD

**Issue by telppa** [snolab/CapsLockX#10]
![image](https://user-images.githubusercontent.com/68984587/114655506-e7e42380-9d1e-11eb-9302-7e98717c6f1b.png)

**Comment by snomiao** [comment]
如何重现？

**Comment by telppa** [comment]
按住capslock不放，帮助弹出，就重现了。或者caps+/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Snowstar ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [snolab/CapsLockX] 帮助里有乱码 caps+/ (#10)





 
如何重现？

**Comment by snomiao** [comment]
检查一下modules/ 里的  鼠标模拟和help的.md文件的编码？

**Comment by telppa** [comment]
跟其它md文件一致，但显示出来有乱码。1.14.37依然乱码。
还有，最下面的说明没有显示完全，也没有滚动条。
建议用edit控件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Snowstar ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 下午3:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [snolab/CapsLockX] 帮助里有乱码 caps+/ (#10)





 
检查一下modules/ 里的  鼠标模拟和help的.md文件的编码？

**Comment by snomiao** [comment]
乱码已修～新版用上edit控件了
