### ISSUE TITLE
请问有把脚本升到V2版本的打算吗？

### ISSUE THREAD

**Issue by cubezhao** [snolab/CapsLockX#100]
最近在使用你脚本中的模拟鼠标功能，觉得用着特别丝滑，我现在主用的版本是V2，所以我想用V2版本实现一下

**Comment by snomiao** [comment]
好啊，我也想升级但最近太忙了。。你可以先自己试试，有进展或问题在这里更新一下

**Comment by cubezhao** [comment]
研究了一下之后发现，使用定时器就可以实现鼠标丝滑移动的效果了，我简单的实现了一下，正常按wasd是鼠标正常速度匀速移动，按住j后变成慢速移动，按住k后变成快速移动，不过老师提供的加速模型确实厉害
