### ISSUE TITLE
caps+f 会一口气滚到页面最下方 刹不住 

### ISSUE THREAD

**Issue by telppa** [snolab/CapsLockX#11]
caps+r正常

**Comment by snomiao** [comment]
你的版本号是？
我这边已确认有些旧版本有这个问题，我这里也有反复出现，修过好几轮……目前最新版在我这正常

**Comment by telppa** [comment]
1.14.35

**Comment by snomiao** [comment]
> 1.14.35

试试新的 1.14.37

**Comment by telppa** [comment]
1.14.37 刹住了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Snowstar ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 下午2:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [snolab/CapsLockX] caps+f 会一口气滚到页面最下方 刹不住  (#11)





  
1.14.35
  
试试新的 1.14.37
