### ISSUE TITLE
关闭窗口功能是否可以有更好的一致性？

### ISSUE THREAD

**Issue by telppa** [snolab/CapsLockX#13]
![TIM截图20210414130919](https://user-images.githubusercontent.com/68984587/114657448-ace3ef00-9d22-11eb-9dc7-511fde5cd04d.png)
例如，在caps+zxcv里，x是 x是关闭窗口 。那么alt+tab里，是否也应该设计为x关闭而不是c？

**Comment by telppa** [comment]
不好意思，帮助看到这里时，没写x，后面写了。

**Comment by snomiao** [comment]
好问题，我把帮助改成X了

`2. 左手窗口管理：在 Alt + Tab 的时候，用 `WASD` 切换窗口，X 关掉窗口`
