### ISSUE TITLE
关于空格键的一点建议。

### ISSUE THREAD

**Issue by telppa** [snolab/CapsLockX#15]
首先，我觉得空格作为触发键挺有创意的，单独用空格+wsad在网页里晃来晃去也挺舒服的。

但是一个显著的问题是，根据我的统计（KMCounter），空格键是每天使用最多的键，显著超越其他键，并且在我看到过的其他所有人那里也是一样。所以，虽然网页里晃悠的时候，这样用着感觉不错，但它完全影响了打字的功能。非常明显的降低了我打字的速度，同时极大的加剧了打字的错误率。

所以，我觉得这是一个破坏性的功能（caps本身很少用，所以怎么改都没啥问题），应该默认不开启，最多最多给一个开关，让用户自己去单独开启。如果一定要默认开启，也需要再思考有没有更好的实现方案。另外，我认真看完了网页全帮助，但是没有写哪里可以关闭空格键的地方。

**Comment by moonhuahua** [comment]
但它完全影响了打字的功能。非常明显的降低了我打字的速度，同时极大的加剧了打字的错误率。

**Comment by moonhuahua** [comment]
但它完全影响了打字的功能。非常明显的降低了我打字的速度，同时极大的加剧了打字的错误率。
我不认同这个说法，我现在用的脚本就完全不影响我打字（我打五笔，打字也不慢的），而且我用了至少2年了的，当然也有可能是我电脑速度比较快的原因吧

**Comment by telppa** [comment]
跟电脑速度没有关系，原因出在原理上。
例如快速的先按空格，然后按c，就会激活窗口重排功能。
那么一个简单的复现场景就是，中文拼音打 “我猜” 两个字，可能是这样输入的 wo空格 cai空格。当整个过程很连续时，明显中间就会变成激活 空格-c 的功能。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月14日(星期三) 晚上9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [snolab/CapsLockX] 关于空格键的一点建议。 (#15)





 
但它完全影响了打字的功能。非常明显的降低了我打字的速度，同时极大的加剧了打字的错误率。
 我不认同这个说法，我现在用的脚本就完全不影响我打字（我打五笔，打字也不慢的），而且我用了至少2年了的，当然也有可能是我电脑速度比较快的原因吧

**Comment by snomiao** [comment]
> 首先，我觉得空格作为触发键挺有创意的，单独用空格 + wsad 在网页里晃来晃去也挺舒服的。
> 
> 但是一个显著的问题是，根据我的统计（KMCounter），空格键是每天使用最多的键，显著超越其他键，并且在我看到过的其他所有人那里也是一样。所以，虽然网页里晃悠的时候，这样用着感觉不错，但它完全影响了打字的功能。非常明显的降低了我打字的速度，同时极大的加剧了打字的错误率。
> 
> 所以，我觉得这是一个破坏性的功能（caps 本身很少用，所以怎么改都没啥问题），应该默认不开启，最多最多给一个开关，让用户自己去单独开启。如果一定要默认开启，也需要再思考有没有更好的实现方案。另外，我认真看完了网页全帮助，但是没有写哪里可以关闭空格键的地方。

好问题，修改配置的方法，拖盘菜单点改配置编辑，然后：
![image](https://user-images.githubusercontent.com/7323030/114825393-bf305c80-9df8-11eb-906c-9c28e1f7280e.png)
在这里可以看到相应的配置选项
![image](https://user-images.githubusercontent.com/7323030/114825931-657c6200-9df9-11eb-9d9d-3b69e4df279d.png)

**Comment by snomiao** [comment]
关于默认配置的问题，下一个版本将会首次启动时自动打开配置文件编辑界面（以后可能考虑提供图形化界面（但是写gui好麻烦orz））

**Comment by telppa** [comment]
哈哈哈 是的 代码5分钟 gui2小时




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Snowstar ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 下午2:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [snolab/CapsLockX] 关于空格键的一点建议。 (#15)





 
关于默认配置的问题，下一个版本将会首次启动时自动打开配置文件编辑界面（以后可能考虑提供图形化界面（但是写gui好麻烦orz））
