### ISSUE TITLE
有一个难以复现的bug

### ISSUE THREAD

**Issue by telppa** [snolab/CapsLockX#17]
似乎每隔20-30分钟，会自动切换一遍虚拟桌面。我已经遇到几次了，当时完全没有碰鼠标键盘，看着桌面自己忽然就切换了。

1.14.37

**Comment by telppa** [comment]
应该是番茄被默认启用了的原因。

**Comment by snomiao** [comment]
默认应该没有启用

**Comment by snomiao** [comment]
找到了，确实启用了。。
