### ISSUE TITLE
caps+f cap+r 模拟滚动, 在不同的应用界面, 灵敏度不一致

### ISSUE THREAD

**Issue by liuxiaoyucc** [snolab/CapsLockX#19]
比如, 我在chrome中使用, 调整到可以接受的加速度, 然后使用企业微信的时候,或者IDE等等, 加速度会变的很大, 会瞬间滑过很远,

每次重新编辑完配置文件, 重载后都会有个弹窗提示, "加载模块帮助遇到错误, 请更新capsx"

还有就是个人体验方面, 比如按住e单击键的同时使用wasd方向键进行选择的时候, 手指会缠绕在一起, 尤其是e和d两个键位😂, 不知道能否支持自定义方向键, 比如改成键盘右侧原本的方向键,或者小键盘等等这样

版本: **1.16.6**

**感谢作者开发这么好用的软件**

**Comment by snomiao** [comment]
> 比如, 我在chrome中使用, 调整到可以接受的加速度, 然后使用企业微信的时候,或者IDE等等, 加速度会变的很大, 会瞬间滑过很远,
> 
> 每次重新编辑完配置文件, 重载后都会有个弹窗提示, "加载模块帮助遇到错误, 请更新capsx"
> 
> 还有就是个人体验方面, 比如按住e单击键的同时使用wasd方向键进行选择的时候, 手指会缠绕在一起, 尤其是e和d两个键位😂, 不知道能否支持自定义方向键, 比如改成键盘右侧原本的方向键,或者小键盘等等这样
> 
> 版本: **1.16.6**
> 
> **感谢作者开发这么好用的软件**

1. 加速度，你可以考虑试试改改系统的滚动行数的设定，我感觉跟那里有关。然后因为默认的加速度指数级别的，起步小，后劲大，你可以考虑基础速度慢一点比较好控制嗯。
2. eh，你可以考虑下个新版本（1.17+）然后在新的位置解压，再把 `config.ini` 移到新目录 `/User/`，出这个错误提示可能有关于我在 1.16 版本左右换过这个目录。
3. 建议多加练习（笑），我的情况是，E和D我是一只食指同时按的（所以就不会缠绕），囧  我感觉这个问题没法用改到别的位置的方式解决 因为鼠标这个东西它就是有这么复杂（移动和滚轮可以理解为  上下左右前后，然后再左右俩按钮，怎么说都得用上8个键的）

**Comment by snomiao** [comment]
![image](https://user-images.githubusercontent.com/7323030/116031546-7a29e700-a690-11eb-8c71-93175eb2ce40.png)
滚动行数设定

**Comment by liuxiaoyucc** [comment]
哈哈哈哈, 感谢, 我现在已经学会了一个食指同时按E&D了, 
但是我又发现一个问题,我用1.17, 每过一段时间, 程序会自动停止运行, 需要手动重启一下, 不知道什么原因
刚看了一下, 已经出了1.18+了, 我更新一下再试试😝

**Comment by snomiao** [comment]
> 程序会自动停止运行, 

有报错吗，如果有的话可否截图

**Comment by liuxiaoyucc** [comment]
> > 程序会自动停止运行,
> 
> 有报错吗，如果有的话可否截图

没有报错, 就是突然那些快捷键都没反应了, 但是右下角小图标还在, 需要重启一下, 有报错我就直接上图了😂

**Comment by snomiao** [comment]
刚刚发布了 1.20.0 版本，对这个issue中的问题应该有改善，你可以试试
