### ISSUE TITLE
模拟鼠标和编辑增强模式下，一直按着 CapsLock 很累

### ISSUE THREAD

**Issue by coreur** [snolab/CapsLockX#21]
**问题一**：

移动鼠标需要按住 CapsLockX + w a s d r f ，这样按 CapsLock 键的手指很累，用空格作为 CapsLockX 打字的时候又容易误触发。

不知道能不能像 vim 一样，触发 CapsLockX 键后进入 CapsLockX 快捷键模式，等再按 CapsLockX / Esc 键退出 CapsLockX 模式。

我的想法是短按 CapsLock 键切换大小写，长按 CapsLock 三秒以上释放进入 CapsLockX 模式，在 CapsLockX 模式下可以直接使用 wasdrf, Shift + r f 来操作鼠标，这样就不用一直按住 CapsLock 键啦。  等再次按 CapsLockX / Esc 键就退出 CapsLockX 模式

---

**问题二**：

CapsLockX + hl 选词在 PDF 软件里面选英文单词只能选中单个字母，判断不了单词

---

**问题三**：

希望能增加光标连选的功能，类似 [Surfingkeys](https://github.com/brookhong/Surfingkeys) 在 V 模式下按住 v + h l

![动画](https://user-images.githubusercontent.com/20869550/128499733-38855713-e3ed-4b9a-bdd5-34c0f3abf3a2.gif)

**Comment by snomiao** [comment]
谢谢你的问题

1.
> 我的想法是短按CapsLock键切换大小写，长按CapsLock三秒以上释放进入CapsLockX模式，在CapsLockX模式下可以直接使用wasdrf, Shift + r f来操作鼠标，这样就不用一直按住CapsLock键啦。 等再次按CapsLockX / Esc键就退出CapsLockX模式

好主意，我将在下一版本中尝试它。

2.
"CLX+hl "相当于 "Ctrl+Left然后Ctrl+Shift+Right"，这在大多数情况下会选择一个单词，但有时PDF阅读器会将单词显示为单独的字符。
我的建议是你可以尝试另一个PDF阅读器，如ABBYY或FireFox...

3.
你可以尝试在浏览器中按F7，然后你可以通过Shift + HJKL选择文本
![image](https://user-images.githubusercontent.com/7323030/128562588-f48a2f6a-d30e-46a3-985e-b8367e83dd5e.png)

**Comment by coreur** [comment]
> 你可以尝试在浏览器中按F7，然后你可以通过Shift + HJKL选择文本

我是想在所有文本编辑器都可以用 v + h / l 光标连选，而不仅仅是浏览器下。  
在光标变成工字形，按住 v + h / l 可以连续选择光标起始位置之间的字符。

**Comment by snomiao** [comment]
> > 你可以尝试在浏览器中按F7，然后你可以通过Shift + HJKL选择文本
> 
> 我是想在所有文本编辑器都可以用 v + h / l 光标连选，而不仅仅是浏览器下。
> 在光标变成工字形，按住 v + h / l 可以连续选择光标起始位置之间的字符。

这个应该按CLX+Shift+H|L就可以做到……如果想从鼠标位置开始，就按CLX+E点一下就好了。
或者是否还有别的理解方式？

**Comment by coreur** [comment]
> > > 你可以尝试在浏览器中按F7，然后你可以通过Shift + HJKL选择文本
> > 
> > 
> > 我是想在所有文本编辑器都可以用 v + h / l 光标连选，而不仅仅是浏览器下。
> > 在光标变成工字形，按住 v + h / l 可以连续选择光标起始位置之间的字符。
> 
> 这个应该按CLX+Shift+H|L就可以做到……如果想从鼠标位置开始，就按CLX+E点一下就好了。
> 或者是否还有别的理解方式？

试了一下可以啦，这条问题解决了，谢谢

**Comment by snomiao** [comment]
1.19.0 版本发布了，实现了CLX 长按1秒进入锁定CLX模式，再短按CLX可退出

**Comment by coreur** [comment]
> 1.19.0 版本发布了，实现了CLX 长按1秒进入锁定CLX模式，再短按CLX可退出

非常好用，现在基本可以实现全程不用鼠标操作电脑啦

目前有一个小问题：退出 CLX 模式/进入 CLX 模式 的悬浮小提示好像不会自动消失

**Comment by snomiao** [comment]
> 目前有一个小问题：退出 CLX 模式/进入 CLX 模式 的悬浮小提示好像不会自动消失
己在新版修复 :D

**Comment by coreur** [comment]
> > 目前有一个小问题：退出 CLX 模式/进入 CLX 模式 的悬浮小提示好像不会自动消失
> > 己在新版修复 :D
完美了，谢谢

**Comment by snomiao** [comment]
#33

**Comment by snomiao** [comment]
目前该功能更新为 同时按空格+CapsLock 进入CLX锁定模式
