### ISSUE TITLE
请问在哪里修改全局系统映射键（caplslockX+M、CapsLockX + /、CapsLockX + Alt + /、CapsLockX + Shift + /）

### ISSUE THREAD

**Issue by peter-dev-dev** [snolab/CapsLockX#22]
你好，我自己习惯把 caplslockX+M 映射成 backspace。所以想问一下如何修改这些全局设置？
（搜索哪里调用 ./User/CapsLockX-Config.ini，但没有找到 open 这个文件的地方，还请指教一下）

- caplslockX+M、CapsLockX + /、CapsLockX + Alt + /、CapsLockX + Shift + /
- 取消“长按 `CapsLockX` 键将锁定 `CLX` 模式”功能

**Comment by snomiao** [comment]
1. `+m` 在`./Modules/插件-用户脚本编辑.ahk` 和 `./Modules/插件-新手教程.ahk` 里
2. 后3个 `/` 的在 `./Modules/00-Help.ahk` 
3. 长按锁定在 `./Core/CapsLockX-Core.ahk` 注释掉 `CapsLockXMode |= CM_CapsLockX`

**Comment by peter-dev-dev** [comment]
谢谢回答，已经搞定
