### ISSUE TITLE
关于空格的触发时间等问题。

### ISSUE THREAD

**Issue by peter-dev-dev** [snolab/CapsLockX#23]
感谢做出这么好的工具，从 mac 迁移到 windows 上后，因为没有 karabiner 所以很好的小白型映射工具。
试用了 capslock+，但以下两个功能是无法实现：
- 使用空格当引导键
- capslock 无法和 shift 待修饰键一起使用

找了一些软件对比后，capslockX 能解决上面的痛点，以后就拿 capslockX 做主力映射工具了。

使用中，还有 3 个小问题。不忙的时候，还请帮忙解答一下：
1，我使用空格当引导键，空格按住“一定时间”后，如果不按任何键就会触发空格键。想把空格触发时间，修改长一些，请问修改哪里？

2， capslock 用来做引导键时，能不能让他不具体有原来的功能（开启/关闭 大写）。也就是说，单按 capslock 键时，不再有开启/关闭功能，但按住 capslock 按时，还可以当引导键来使用。请问这个功能如何修改好一些？

3，想按住“capslock + shift + h/l”键，进行选择向左/右进行选择。如果先按住 caplock 键，再按住其它两个键没有问题，能正常启动映射。但如果先按住 shift 键，再按住 capslock 键，就无法启动映射。请问这个要怎么修改好？

**Comment by snomiao** [comment]
首先感谢提问，

1.
见 `CapsLockX-Core.ahk` 如图，修改此处 1000 为 CLX 长按判定的时间，单位为毫秒
![image](https://user-images.githubusercontent.com/7323030/130312933-186e12fb-2cf4-40c9-9f01-86c95e63c456.png)

见 `CapsLockX-Core.ahk` 如图，修改此处 200 为按住空格触发空格键判定的时间，单位为毫秒
![image](https://user-images.githubusercontent.com/7323030/130312954-07bc05ec-226d-47a1-9aa5-436b316904c0.png)

2. 见 `CapsLockX-Core.ahk` 如图，还原按键功能的代码，如果不需要（也就是说CapsLock不切换，或空格不触发）的话可以直接整块注释掉。
![image](https://user-images.githubusercontent.com/7323030/130312847-75670455-cb47-4019-aa3f-7f7b98fb93d1.png)

3. 这样设计的原因如下：由于例如 Shift+空格 和 Alt+空格 这样的热键存在，所以CLX在当做CLX用的时候一般是作为先按下的那个键使用，如果不是这样的话就会覆盖掉前述2个热键。

如果想要试试先按Shift再按CLX键也可以生效的效果的话，可以按下图所示修改，不过我不确定这样会引发什么样的BUG……如果你试了有什么心得体会的话欢迎反馈到这里 :D

见 `CapsLockX-Core.ahk` 如图，给每个热键前加*号。（也许再下面 Up 的热键也要加，你应该可以自己找到）
![image](https://user-images.githubusercontent.com/7323030/130313138-770b59d5-7134-46fa-b7f1-efa79cc3e415.png)

**Comment by peter-dev-dev** [comment]
感谢回复。

1，这个问题 OK 了。

2，关于这个问题，还有一点小问题。
在单按 capslock 时，已经没有 capslock 的功能了。capslock + h/l 等键也可以正常映射。
但如果先按 shift，再按 capslock 的话，就会触发 capslock 的功能（即，开启了大写）。
（本功能的修改，是使用原始代码，只修改上面第2点要修改的代码，测试完成的。所以可以排除因为其它的功能修改，造成这个问题的原因。）

3 ，我是按上面的图片上修改的，功能好像不好用。即，先按 shift，再 capslock 没有实现“ capslock + shift + key” 的功能。
（本功能的修改，是使用原始代码，只修改上面第3点要修改的代码，测试完成的。所以可以排除因为其它的功能修改，造成这个问题的原因。）

```
Hotkey, If, CapsLockX_Avaliable()

if(T_XKeyAsCapsLock) 
    Hotkey *CapsLock, CapsLockX_Dn
if(T_XKeyAsSpace) 
    Hotkey *Space, CapsLockX_Dn
if(T_XKeyAsInsert)
    Hotkey *Insert, CapsLockX_Dn
if(T_XKeyAsScrollLock)
    Hotkey *ScrollLock, CapsLockX_Dn
if(T_XKeyAsRAlt)
    Hotkey *RAlt, CapsLockX_Dn

Hotkey, If, !CapsLockX_Avaliable()

if(T_XKeyAsCapsLock) 
    Hotkey *CapsLock, CapsLockX_NotAvaliable
if(T_XKeyAsSpace) 
    Hotkey *Space, CapsLockX_NotAvaliable
if(T_XKeyAsInsert)
    Hotkey *Insert, CapsLockX_NotAvaliable
if(T_XKeyAsScrollLock)
    Hotkey *ScrollLock, CapsLockX_NotAvaliable
if(T_XKeyAsRAlt)
    Hotkey *RAlt, CapsLockX_NotAvaliable

Hotkey, If

if(T_XKeyAsCapsLock)
    Hotkey *CapsLock Up, CapsLockX_Up
if(T_XKeyAsSpace) 
    Hotkey *Space Up, CapsLockX_Up
if(T_XKeyAsInsert)
    Hotkey *Insert Up, CapsLockX_Up
if(T_XKeyAsScrollLock)
    Hotkey *ScrollLock Up, CapsLockX_Up
if(T_XKeyAsRAlt)
    Hotkey *RAlt Up, CapsLockX_Up
```

**Comment by snomiao** [comment]
> 感谢回复。
> 
> 1，这个问题 OK 了。
> 
> 2，关于这个问题，还有一点小问题。
> 在单按 capslock 时，已经没有 capslock 的功能了。capslock + h/l 等键也可以正常映射。
> 但如果先按 shift，再按 capslock 的话，就会触发 capslock 的功能（即，开启了大写）。
> （本功能的修改，是使用原始代码，只修改上面第2点要修改的代码，测试完成的。所以可以排除因为其它的功能修改，造成这个问题的原因。）
> 
> 3 ，我是按上面的图片上修改的，功能好像不好用。即，先按 shift，再 capslock 没有实现“ capslock + shift + key” 的功能。
> （本功能的修改，是使用原始代码，只修改上面第3点要修改的代码，测试完成的。所以可以排除因为其它的功能修改，造成这个问题的原因。）
> 
> ```
> Hotkey, If, CapsLockX_Avaliable()
> 
> if(T_XKeyAsCapsLock) 
>     Hotkey *CapsLock, CapsLockX_Dn
> if(T_XKeyAsSpace) 
>     Hotkey *Space, CapsLockX_Dn
> if(T_XKeyAsInsert)
>     Hotkey *Insert, CapsLockX_Dn
> if(T_XKeyAsScrollLock)
>     Hotkey *ScrollLock, CapsLockX_Dn
> if(T_XKeyAsRAlt)
>     Hotkey *RAlt, CapsLockX_Dn
> 
> Hotkey, If, !CapsLockX_Avaliable()
> 
> if(T_XKeyAsCapsLock) 
>     Hotkey *CapsLock, CapsLockX_NotAvaliable
> if(T_XKeyAsSpace) 
>     Hotkey *Space, CapsLockX_NotAvaliable
> if(T_XKeyAsInsert)
>     Hotkey *Insert, CapsLockX_NotAvaliable
> if(T_XKeyAsScrollLock)
>     Hotkey *ScrollLock, CapsLockX_NotAvaliable
> if(T_XKeyAsRAlt)
>     Hotkey *RAlt, CapsLockX_NotAvaliable
> 
> Hotkey, If
> 
> if(T_XKeyAsCapsLock)
>     Hotkey *CapsLock Up, CapsLockX_Up
> if(T_XKeyAsSpace) 
>     Hotkey *Space Up, CapsLockX_Up
> if(T_XKeyAsInsert)
>     Hotkey *Insert Up, CapsLockX_Up
> if(T_XKeyAsScrollLock)
>     Hotkey *ScrollLock Up, CapsLockX_Up
> if(T_XKeyAsRAlt)
>     Hotkey *RAlt Up, CapsLockX_Up
> ```

想起来了还有一个这个地方会影响
![image](https://user-images.githubusercontent.com/7323030/130324723-c5e44743-8e33-4757-9457-efe1ac78a96d.png)

**Comment by peter-dev-dev** [comment]
关于第2点，注释了 capslockx_dn() 方法里面的代码还是不行，还是有上面问题。
请问还有其它地方需要注释吗？

**Comment by snomiao** [comment]
迷……

**Comment by peter-dev-dev** [comment]
谢谢回复，那这个问题先关了吧
