### ISSUE TITLE
自动重载模块出错，以及一些希望和建议

### ISSUE THREAD

**Issue by Force1ess** [snolab/CapsLockX#24]
在我使用的过程中，自动重载模块一直不停的提示配置文件修改，是否自动重载，并且每3s左右就会有个弹窗
如果难以修复此bug，希望能提供关闭弹窗的功能
建议：
1、给出指针加速度开关，加速度的好处是能够快速点击远处的目标，但是对于中距离的目标（例如当鼠标指针移动半屏）的时候，加速度会让鼠标难以一次完成点击
2、给出鼠标速度调节
3、不要使用长按的方式来切换CLX模式，当需要在两种模式之间频繁切换的时候，长按会让整个流程变得繁琐，使用组合键例如Ctrl+Caps来切换
4、修复鼠标左键长按BUG，当长按E拖动进度条时，经常会出现拖不动的情况，比如你们出现的配置文件那里就拖不动
5、给出反转Q、E的选项，Q在左但代表鼠标右键，E在右但代表鼠标左键，使用起来不时很直观
感谢您的无私奉献，以上是我的个人建议

**Comment by snomiao** [comment]
感谢建议！

问题反馈：
 - `在我使用的过程中，自动重载模块一直不停的提示配置文件修改，是否自动重载，并且每3s左右就会有个弹窗`
自动重载原理是监视配置文件夹变动，频率高到 3s 应该是有其它软件在修改配置目录里的文件（同步软件等）。
我会在启动配置里加上关闭重载功能的选项。

建议反馈：
1. 按住Shift可以让指针加速度变慢，不知是否你想要的功能
2345无异议，预计将来版本会修改。

**Comment by Force1ess** [comment]
好的，感谢您的工作！
祝一切顺利
