### ISSUE TITLE
模拟鼠标滚轮对于多显示器的支持

### ISSUE THREAD

**Issue by TC-Mits-Qine** [snolab/CapsLockX#25]
垂直滚轮（上下）_[CapsLockX + r f_] 和水平滚轮（左右）_[CapsLockX + Shift + r f]_ 在电脑连接多台显示器时，在副显示器上无法正常触发，已授予管理员权限。

----------------
13日晚更新详细问题描述

![Snipaste_2021-12-13_21-30-46](https://user-images.githubusercontent.com/32544907/145821460-f7e7465a-6705-47fe-b4f0-550534f5b892.png)

操作系统版本 22518.1000
CapsLockX-v1.21.2
笔记本电脑 + HDMI 外接显示器
华硕天选(FA506IV) + 飞利浦 245B
电脑无独显直连功能，两块屏幕均由 AMD 核显输出

怀疑与光标位置有关而与窗口位置无关，当光标在副屏幕内时，所有的窗口上都无法使用模拟鼠标滚轮；把窗口放在两块屏幕交界处，只要光标位于副屏就无法滚动，且光标回到主屏幕内时立即恢复正常。

将笔记本屏幕设为主屏幕后，上述问题消失。

**Comment by snomiao** [comment]
我这里还没测出过此现象，可否了解一下你的设备情况？以便排查问题。

1. 操作系统版本，开始运行输入winver
2. 比如屏幕分辨率和DPI和位置之类？
比如：![image](https://user-images.githubusercontent.com/7323030/145795866-8506418a-634f-4361-ac0b-1e84d2d501b3.png)
3. 所使用的 CapsLockX 版本号

**Comment by snomiao** [comment]
4. 以及在什么窗口上出问题，还是所有窗口上都有问题？

**Comment by snomiao** [comment]
了解了，这应该是Win11窗口管理器适配问题，我过几天有空装一个测试测试哈

**Comment by snomiao** [comment]
更新了 1.21.3 版本，把滚轮 API 换成了 SendInput ，你试试
