### ISSUE TITLE
关于加载插件的问题

### ISSUE THREAD

**Issue by Lovening** [snolab/CapsLockX#27]
能否有个配置文件可以自定义设置加载哪些插件，比如有些插件对于我来说并没有用，我只想用编辑的功能，其他的功能都用不上，是否可以有个配置文件来设置哪些功能不加载，哪些功能加载

**Comment by snomiao** [comment]
好！安排！

**Comment by snomiao** [comment]
现在按CLX+M打开配置文件可以编辑禁用模块了 
![image](https://user-images.githubusercontent.com/7323030/154512386-3f37271b-e406-44f4-b9ea-31b763f598cc.png)
