### ISSUE TITLE
文档错误#DD#和#TT#无效

### ISSUE THREAD

**Issue by Sam7Joker** [snolab/CapsLockX#28]
你好，秒打时间戳中文档中#DD#和#TT#无效。
![image](https://user-images.githubusercontent.com/30770798/154175672-0c2c24ca-ce66-4365-90c7-494b7cd9afb5.png)
代码中也没有#DD#和#TT#的关键字。

**Comment by snomiao** [comment]
感谢反馈！下个版本会更新相应文档。
