### ISSUE TITLE
编辑增强长时间按住松开后光标没有立刻停止

### ISSUE THREAD

**Issue by Sam7Joker** [snolab/CapsLockX#29]
较长时间按住CapsLock+j/k，在光标快速移动一段时间后松开按键。光标没有停止而是继续向上或者向下一段时间才停止。
不知道是不是有意设置的？

**Comment by snomiao** [comment]
是有意的 :D

**Comment by snomiao** [comment]
模拟鼠标的移动也是同一个加速模型，会在放开后减速再停止（其实现实世界中的刹车也没有能马上停下的），你可以预判好目标位置提前放手。

**Comment by snomiao** [comment]
btw 你也可以放开clx键来强制停止

**Comment by qstdnx** [comment]
> btw 你也可以放开clx键来强制停止

有无地方关闭编辑的加速模型呢，感觉光标还是不要加速比较好用点。
