### ISSUE TITLE
建立增加caps+enter实现不折行回车

### ISSUE THREAD

**Issue by fatway** [snolab/CapsLockX#32]
从capslock+迁移过来的用户，很多键都适应过来了，唯独没有 caps+回车 实现不折断文字直接换行这功能。
你能体会到vim用户没有o键的感觉吗？

**Comment by snomiao** [comment]
相当于 End + Enter ?

**Comment by snomiao** [comment]
Done for 1.23.0

**Comment by snomiao** [comment]
Done for 1.23.0

**Comment by fatway** [comment]
> Done for 1.23.0

thx，就是这个feel
