### ISSUE TITLE
[建议]增加backspace删除整行

### ISSUE THREAD

**Issue by fatway** [snolab/CapsLockX#33]
我在CapsLockX-EnterWithoutBreak.ahk最后增加了以下内容，想实现 caps+backspace 删除当前整行文字的功能（相当于vim中的dd）

```
; 删除整行
BackSpace:: Send {End}{Shift Down}{Home}{Shift Up}{BackSpace}
```

目前功能已经实现了，不知道是不是最优解，有时候使用caps+...组合时会出现莫名的紊乱，不知是不是自己加的这个地方引起。

- - -
另外还想请教下，长按 CapsLockX 键进入的锁定 CLX 模式，这个功能个人很不习惯，经常引起误操作。请问如果屏蔽掉CLX模式？

**Comment by snomiao** [comment]
; tested in vscode multiline mode
Enter:: SendEvent {End 2}{Enter} ; 行尾回车
BackSpace:: SendEvent {Home 2}{End}{Home 2}+{End 2}+{Right}{Delete} ; 删除整行

**Comment by snomiao** [comment]
CLX长按锁定模式会在新版本屏蔽，
旧处代码在  CapsLockX-Core.ahk 里搜 `if ( A_TickCount - CapsLockPressTimestamp > 1000) {` 可按需修改

**Comment by fatway** [comment]
> ; tested in vscode multiline mode Enter:: SendEvent {End 2}{Enter} ; 行尾回车 BackSpace:: SendEvent {Home 2}{End}{Home 2}+{End 2}+{Right}{Delete} ; 删除整行

使用sendevent会有很明显的操作轨迹，感觉运行速度和效率上不如原来的send快

**Comment by snomiao** [comment]
> 使用sendevent会有很明显的操作轨迹，感觉运行速度和效率上不如原来的send快

什么环境？系统？软件？

**Comment by fatway** [comment]
win10, vscode下sendevent操作轨迹有一点点，sublime text更明显一些

**Comment by snomiao** [comment]
done
