### ISSUE TITLE
docs: keymap picture 有没有键位说明图之类的

### ISSUE THREAD

**Issue by hertymarcellus** [snolab/CapsLockX#34]

**Comment by snomiao** [comment]
还没

**Comment by snomiao** [comment]
谁比较擅长画东西的可以来画个 :D

**Comment by moonhuahua** [comment]
有，我做了很多常用软件的键位图，比如
![image](https://user-images.githubusercontent.com/15684037/157218456-601e9c3d-7fc0-4f8b-8050-b9f0b914e1f5.png)

**Comment by snomiao** [comment]
wow, 这种风格就很直观
