### ISSUE TITLE
请问，如何设置短按capslock为Esc按键？

### ISSUE THREAD

**Issue by zhuchengxue** [snolab/CapsLockX#36]
因为之前一直使用类vim插件比如surfingkeys, 为方便就把capslock按键改成了esc， 请问大大如何修改

**Comment by snomiao** [comment]
![image](https://user-images.githubusercontent.com/7323030/162402332-2547cb50-c55b-4177-8a29-36572e2a059c.png)
供参考


(20220408) btw, 请关注上海断粮。

**Comment by zhuchengxue** [comment]
谢谢大佬回复，感谢您的时间，会持续关注
