### ISSUE TITLE
按空格后很久按capslock键依然会进入CLX模式

### ISSUE THREAD

**Issue by qstdnx** [snolab/CapsLockX#39]
请问作者大大，设定上是否是同时按space+capslock会触发CLX模式，但是我这里按空格后隔很久按capslock键也马上会进入clx模式，很干扰打字，打完中文最后通常是按空格，如果要移动光标马上会自动进入CLX模式。

**Comment by snomiao** [comment]
给你加了个 250ms 的阈值  :D

**Comment by qstdnx** [comment]
> 给你加了个 250ms 的阈值 :D

问题已完美解决  感谢大佬
