### ISSUE TITLE
增加开机自启功能

### ISSUE THREAD

**Issue by maiixu** [snolab/CapsLockX#42]
非常棒的效率辅助工具，然而每次开机之后需要重新运行脚本。希望作者能够在配置文件/脚本中加入开机自启动选项。
环境：Windows 10 家庭版
安装方式：命令行（npx安装）

**Comment by snomiao** [comment]
目前第一次启动时候自动弹出的配置界面有开机自启动的选项，

不过我不清楚 npx 安装会不会有重启清除文件的程序，你可以帮我测试一下吗。

如果是会清理的话，也许就需要把自启动的方法换成 npx -y -- capslockx 之类的东西了

**Comment by maiixu** [comment]
> 
我把配置文件里的FIRST_LAUNCH参数改为1，似乎没有跳出带有开机自启动的先项。重启之后会清除文件，因为每次重启之后都需要跑'npx capslockx'命令重新安装。

**Comment by snomiao** [comment]
```cmd
echo npx -y -- capslockx > %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\capslockx-startup.bat
```
你可以先运行一个上面的脚本加自启动，我这几天还忙，等有空了再研究一下搞个判断安装方式加自启动的功能哈。

**Comment by snomiao** [comment]
哦不是选项，是一个按钮

![image](https://user-images.githubusercontent.com/7323030/165190857-b5ef424e-ffcb-4076-8e74-445c470d9cb4.png)


> > 
> 
> 我把配置文件里的FIRST_LAUNCH参数改为1，似乎没有跳出带有开机自启动的先项。重启之后会清除文件，因为每次重启之后都需要跑'npx capslockx'命令重新安装。

**Comment by maiixu** [comment]
我试了一下这个开机自启功能，会在Microsoft\Windows\Start Menu\Programs\Startup\文件夹下建立一个capslockx-startup.bat文件。但是开机启动的时候跑这个bat文件不会唤起软件，所以后来我把exe文件的快捷方式扔进去解决了。

**Comment by snomiao** [comment]
Nice
