### ISSUE TITLE
Caplock + hl 出现一次跳跃多个字符现象

### ISSUE THREAD

**Issue by maiixu** [snolab/CapsLockX#43]
**问题描述：**
非常喜欢caplock+hjkl的vim风格导航键位。实测发现Caplock+H键或者Caplock+L键会出现一次跳跃两个字符或者多个字符的情况，有些类似有些鼠标宏定义里的Smart滚轮功能，即在检测到用户大幅度翻页时加快翻页速度。然而Caplock+HL键跳跃字符触发概率有些高，实际影响使用。

**解决方案：**
可以去除该功能/修改BUG或者减少触发条件。支持回归vim操作习惯（即HL每次移动一个字符）。

**Comment by snomiao** [comment]
猜测应该是我启动阈值设的比较低的缘故
研究了一下是光标移动速度设的比较高的缘故

**Comment by snomiao** [comment]
光标速度从50改低到15了，应该能符合大多数人的操作速度习惯。有提速需求的就自己改配置文件吧（笑

**Comment by snomiao** [comment]
更新在了 1.25.9

**Comment by maiixu** [comment]
测试了新版本很理想，作者大大辛苦！

**Comment by WalkerGloom** [comment]
> 光标速度从50改低到15了，应该能符合大多数人的操作速度习惯。有提速需求的就自己改配置文件吧（笑

之前也发现了这个问题，尝试着把EditEnhance下的SpeedRatioX从1改为0.5也可以解决
