### ISSUE TITLE
ask: emerge stop 编辑增强如何急停

### ISSUE THREAD

**Issue by qstdnx** [snolab/CapsLockX#44]
如何关掉这个减速的功能呢？
长按之后放开还会自己往前跑好久，跑的比我按得还久，放开capx键也没用，几乎没法停在自己想要的位置。

**Comment by snomiao** [comment]
设计上是放开CapsLockX会急停，这应该是bug

**Comment by snomiao** [comment]
操作系统和版本，clx版本，ahk版本，在什么软件上出这个问题，发一下看看

**Comment by qstdnx** [comment]
> 操作系统和版本，clx版本，ahk版本，在什么软件上出这个问题，发一下看看

版本 21H1 (操作系统内部版本 19043.1620)
clx版本1.25.5
ahk版本1.1.31.1
所有软件都是这样。

可以远程协助查找问题。

**Comment by snomiao** [comment]
加我tg @snomiao

qstdnx ***@***.***> 于2022年5月5日周四 20:46写道：

**Comment by qstdnx** [comment]
是这个吗
![image](https://user-images.githubusercontent.com/20844622/167260730-101934d9-7eca-44af-b0db-10689cee6351.png)

**Comment by snomiao** [comment]
yep and you can try this group https://t.me/capslockx

Issues-translate-bot ***@***.***> 于2022年5月7日周六 23:23写道：

**Comment by qstdnx** [comment]
已加tg群，其他bug在群里反馈了
