### ISSUE TITLE
bug: slowly doc loading 项目的说明网站加载时间太长-能否加速加载

### ISSUE THREAD

**Issue by lingr7** [snolab/CapsLockX#49]
加载时间太长差点就放弃了，放在一边等了很久。
建议优化，提升项目体验。

**Comment by snomiao** [comment]
地址？

**Comment by lingr7** [comment]
[capslockx.snomiao.com](https://capslockx.snomiao.com/)

**Comment by snomiao** [comment]
我这里打开还蛮快的。这个网站是挂的 cloudflare 的cdn，你的地理位置和网络是哪家的？有没有翻墙？这几年墙内线路看着不太好，得另外想办法优化。

**Comment by lingr7** [comment]
> 我这里打开还蛮快的。这个网站是挂的 cloudflare 的cdn，你的地理位置和网络是哪家的？有没有翻墙？这几年墙内线路看着不太好，得另外想办法优化。

上海，公司用网，不知道哪家，今天打开网站速度很快，体验很好。
