### ISSUE TITLE
feat: window-binding 增加窗口绑定功能

### ISSUE THREAD

**Issue by Guiquan-27** [snolab/CapsLockX#51]
可否增加像capslock+一样绑定到窗口的功能？真的日常很需要的，尤其是多窗口操作的时候，感谢！
实在不想用tab之后还要经过选择才能确认那个窗口

**Comment by snomiao** [comment]
你可以再详细描述一下你想要的效果或者把capslockx+的对应讲这个功能的文档链接给我

**Comment by Guiquan-27** [comment]
> 你可以再详细描述一下你想要的效果或者把capslockx+的对应讲这个功能的文档链接给我

[https://capslox.com/capslock-plus/#clWinBind](url)
这里面其中winbind的部分。
谢谢~

**Comment by snomiao** [comment]
你的需求对应CLX下的实现，应该比较近似于虚拟桌面1 2... 9 0的切换功能。比如说你把当前窗口按CLX+Shift+3移到虚拟桌面3，然后就相当于把窗口绑定到了3号桌面，要切换过去的话按 CLX+3 就可以切换到3号桌面。
用这个方法就相当可以同时绑定许多窗口到一个热键上。

**Comment by Guiquan-27** [comment]
> 
好的，感谢。我自己试试。
