### ISSUE TITLE
FR: 增加对supermemo的支持

### ISSUE THREAD

**Issue by YIRU69** [snolab/CapsLockX#54]
搜了一下发现了宝藏，很感谢作者的付出，
我的Ahk 还不太多，现在自己使用supermemo，能否像作者写了anki一样，来支持supermeemo呢
出一个教程也行
求求了

**Comment by snomiao** [comment]
Yep It's a good idea, tough I have no licence to use supermemo :(

**Comment by snomiao** [comment]
## 基本思路
1. 基本上你可以直接研究一下AHK的教程然后写一个可以独立运行的脚本来增强你的SuperMemo
2. 把它扔进 CapsLockX 的 Modules 目录里，重启 CapsLockX。
3. 如果没问题的话，就相当于插件安装成功了。
4. 如果有报错的话，检查一下有什么函数有可能跟别的插件模块或者clx本身冲突的。

## 其它

作为CapsLockX的插件而不是独立脚本，有一些预定义的变量可以用：

###  CapsLockX_THIS_MODULE_HELP_FILE_PATH 变量
是当前模块的同名 .md 文件的路径

```ahk
CapsLockX_ModuleSetup_4:
    CapsLockX_THIS_MODULE_HELP_FILE_PATH = ./Modules/01.1-插件-鼠标模拟.md
    #Include ./Modules/01.1-插件-鼠标模拟.ahk
Return
```

### CapsLockXMode 变量

在 #if 条件里加入 CapsLockXMode，作用域内的的所有热键都会变成 CapsLockX + 该热键。

例如如果这样写一个模块，就创建了3个CLX热键：CLX+X, CLX+Q, CLX+C，且只在Anki窗口内生效

```ahk
#if CapsLockXMode && ( WinActive("Anki -.* ahk_class QWidget ahk_exe anki.exe") || WinActive("Anki - .*|.* - Anki ahk_class Qt5QWindowIcon ahk_exe anki.exe"))

$x:: Send s ; study
$q:: Send d ; quit
$c:: Send a ; create

```

**Comment by YIRU69** [comment]
感谢

**Comment by snomiao** [comment]
追问进展 :D
