### ISSUE TITLE
想问一下这里用的autohotkey是什么版本的？

### ISSUE THREAD

**Issue by chenerg** [snolab/CapsLockX#55]
纯好奇

**Comment by snomiao** [comment]
应该是 1.1.26.x ? 我不太确定了，不过最近可以升级一下

chenerg ***@***.***> 于2022年7月29日周五 22:29写道：

**Comment by chenerg** [comment]
感谢 看到autohotkey更新了新的版本 语法好像变化挺大的 也不知道也没有带来什么好效果
