### ISSUE TITLE
莫名其妙无法运行了

### ISSUE THREAD

**Issue by MysticDragonfly** [snolab/CapsLockX#57]
错误类型error in # include file
"D:\desktop\CapsLockX-v1.28.4\Modules\03-VirtualDesktop.ahk":
Call to nonexistent function.
报错在228行228:listOfWindow :WindowsListOfMonitorFast(arrangeFlags|....
之前是没有这个错误的。之前ahk脚本开着也可以正常运行，现在是关掉所有的ahk脚本之后都无法正常运行。我通过注册表，修改过键盘映射，这个是否会有影响？

**Comment by MysticDragonfly** [comment]
雪星大佬 ，你好，非常感谢你开发的这款capslockx工具，虽然我这里不能用，但是太喜欢你做的这个鼠标了。幸好它使用ahkv1编写，我折腾了很久，把鼠标单独拿出来了。相信会有一些朋友也是被这个鼠标吸引来的，独立出来以后我叫它雪星鼠标。我没法上传文件，通过连接把热键调用方式分享出来吧。https://wwm.lanzouy.com/i7rZY0dzz9gj

**Comment by snomiao** [comment]
下载一个新版本有这个问题吗？

安装渠道是 npm还是chocolatey还是从release装的？
