### ISSUE TITLE
FR：同类插件Capslock++拥有的翻译功能能够通过CapslockX实现吗

### ISSUE THREAD

**Issue by SorrowableCode** [snolab/CapsLockX#58]
如题，目前没有看到实现类似功能的模块，各位查看各种英文资料的时候又是翻译功能的呢，有没有比较好的方法

**Comment by snomiao** [comment]
提上日程，请介绍一下具体希望的体验，比如按什么键出什么介面之类

此外再介绍下它应该比 CopyTranslate 有的优势在哪
