### ISSUE TITLE
bug: js功能异常

### ISSUE THREAD

**Issue by kazetyan** [snolab/CapsLockX#59]
复现
1. 选中`1+1`
2. 按下CapsLock + -
3. 提示需安装node

![image](https://user-images.githubusercontent.com/50894526/199210390-4ee5f577-6b64-4007-908c-cce4c1c0fac4.png)

**Comment by snomiao** [comment]
符合设计，确实需要装NodeJS

**Comment by snomiao** [comment]
噢我知道了你的node是不是装在cygwin下的，应该是路径没识别上

**Comment by kazetyan** [comment]
不是哦,是安在win下的
![image](https://user-images.githubusercontent.com/50894526/199868755-411116bb-4518-4cb8-a20f-b73828e0af08.png)
识别路径的逻辑是什么呢,估计是和我配的环境变量不一样导致没识别到?
