### ISSUE TITLE
shift 键关闭大写锁定失效

### ISSUE THREAD

**Issue by teteko233** [snolab/CapsLockX#62]
OS： win11 Home Edition

软件版本：1.30.3

描述：

当设定按 Shift 关闭 Capslock 时，会出现大写无法关闭的情况

![image.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v2397b7671770d4313be4eca6b241ff075.png)

通过键盘录制软件捕捉到，当系统使用 shift 关闭 Capslock 时，实际执行的按键为 Shift-Capslock ，但运行脚本以后，按下 Shift，实际执行的按键为 Shift。

建议:

按下 Shift 时，判断当前是否处于大写锁定状态，若处于，则执行 Shift-Capslock

**Comment by snomiao** [comment]
可以重現，但很難修，因爲capslockx本身并不直接處理 Shift 键，经过测试，按 shift 時也没有触发 CapsLock 键……
如果你有思路的话可以尝试修改 capslockx-core.ahk 以及 PR 到本倉庫。
