### ISSUE TITLE
[Feature suggestion] Reload CLX quickly with vanilla keyboard shortcuts in Windows. | 利用 Windows 内置的快捷键快速重新加载CLX

### ISSUE THREAD

**Issue by shiyuwang-jamk** [snolab/CapsLockX#66]
As long as CLX and its AHK processes are still running, one could press `Win + B`, locate the CLX icon, press menu key, and select 'Reload CapsLockX' to reload the mouse emulation. That would save much time without any further modification / addition.

What about keeping the CLX icon the first icon in the tray, so that one would be able to have the keyboard focus right on the CLX icon with a single key combination? Just as Windows 10 decided to have dedicated screen keyboard / virtual touchpad / Windows Ink button following the notification icons, CLX can stand out by keeping its spot as accessible as any stock features that come with vanilla Windows experience.

**Comment by snomiao** [comment]
great idea

2023年2月6日(月) 23:12 Wang Dani ***@***.***>:

**Comment by snomiao** [comment]
not stale

**Comment by shiyuwang-jamk** [comment]
Okay, how about a customized item in Win + X context menu? Just add the shortcut as the first in the first group of shortcuts.

**Comment by snomiao** [comment]
Seems not reasonable to modify system menu since it would be what virus are
doing

**Comment by shiyuwang-jamk** [comment]
So this will probably be an automated procedure within CLX, but one can use third-party tools to make a shortcut to CLX in Win+X menu, like this one updated in 2017: https://winaero.com/winx-menu-editor-for-windows-10-and-windows-8/

**Comment by snomiao** [comment]
yap its possible

**Comment by shiyuwang-jamk** [comment]
One can do this themselves, does not have to be part of CLX itself.
