### ISSUE TITLE
[question]自定义快捷键冲突:定义clk+n = insert,按alt+clk+n先触发alt+n而不是alt+insert

### ISSUE THREAD

**Issue by kazetyan** [snolab/CapsLockX#69]
rt,请问下应该怎样处理?
现在是这样使用的
`n:: Send {Ins}`

**Comment by snomiao** [comment]
1. 可否分享一下你的branch

2. 一般是建議這様用，可以把其它的alt之類也包含進来
```
#if CapsLockXMode
n:: {Ins}
```

3. 提問時建議区分一下先 1:你現在按出来的効果是什麼，後2: 你希望按出来的効果是什麼

4. 先按 alt 的情況 space 只做空格使用，如果你需要触発clx，得先按CLX再按alt。
5.

**Comment by kazetyan** [comment]
1. 我就是在`03.1-WindowManager.ahk`原来的基础上加了个`n:: Send {Ins}`
![image](https://user-images.githubusercontent.com/50894526/223981595-3b8b8a8d-f213-433a-ac81-93714e12671e.png)
1. `n:: {Ins}` 这样使用提示错误
![image](https://user-images.githubusercontent.com/50894526/223982065-6e790987-19ea-42d4-8e1a-e1961414a61f.png)
2. 假设个前提按alt+n输出1,按alt+ins输出2;当我按键alt+clk+n时,现在的效果:先触发alt+n的快捷键输出1,期望的效果:触发alt+ins快捷键输出2
3. 无论是alt+clk+n,还是clk+alt+n,都是触发alt+n

**Comment by snomiao** [comment]
由於 alt+space 已経是 窗口左上角菜単的熱鍵所以4不能実現
不過 alt+capslock+n 応該可以，這様子有問題嗎

**Comment by kazetyan** [comment]
我没有用空格,我的启动键是capslock,上述clk指的是capslock按键

**Comment by snomiao** [comment]
我測試了 alt+capslock+h 可以正常触発 alt+left
対了，保留alt需要 Send {Blink}{Ins}

**Comment by snomiao** [comment]
可以考慮
*n:: Send {Blink}{Ins}

**Comment by snomiao** [comment]
参考如下
```autohotkey
#if CapsLockXMode

; 鼠标运动处理
*a:: 鼠标模拟.左按("a")
*d:: 鼠标模拟.右按("d")
*w:: 鼠标模拟.上按("w")
*s:: 鼠标模拟.下按("s")

```

**Comment by kazetyan** [comment]
还是不行
好像ins不太一样,你用`shift+ins`来试试,这应该是win自带的粘贴
`n:: Send {Ins}` 时,`shift+capslock+n`输出`N`
`+n:: Send {Blink}{Ins}`时,`shift+capslock+n`触发ins切换光标输入模式
都不能触发粘贴

**Comment by snomiao** [comment]
噢 blind打錯了，我測試了這様可以粘貼

*m:: Send {Blind}{Insert}

**Comment by kazetyan** [comment]
可以了,感谢😄
