### ISSUE TITLE
hi, 关于空格键和capsLock的细节...

### ISSUE THREAD

**Issue by WillDawnlll** [snolab/CapsLockX#7]
首先感谢作者的脚本..主要问下空格和capslock使用是有没有区别..
capslock和esc交换了在左上角比较远, 看脚本里有space所以简单试了一下发现应该和capslock差不多, 但是对ahk语法不熟还是想再确认一下....
以及如果想映射到win键, 在脚本功能范围内有没有什么冲突的(win 的映射改setting.ahk里面为win吗....还是ini文件...),space用来作vim的leader了...

**Comment by WillDawnlll** [comment]
...还有..用jk上下的是时候有1/3会触发两次(按一下j下移两行)

**Comment by WillDawnlll** [comment]
- 看代码好像jk的时候必须capslock和jk等键一起松才能立即停下? 但是里面有一些变量看名称不好猜作用, 求简单解释一下....
- 比如这里的mtl mtr mtu tda 之类........
![图片](https://user-images.githubusercontent.com/28567110/107135986-6052f080-693a-11eb-9aaa-a5d0b24b59c5.png)

**Comment by WillDawnlll** [comment]
...直接改加速度了...再次感谢这个工具和作者

**Comment by snomiao** [comment]
12
> 首先感谢作者的脚本..主要问下空格和capslock使用是有没有区别..
> capslock和esc交换了在左上角比较远, 看脚本里有space所以简单试了一下发现应该和capslock差不多, 但是对ahk语法不熟还是想再确认一下....
> 以及如果想映射到win键, 在脚本功能范围内有没有什么冲突的(win 的映射改setting.ahk里面为win吗....还是ini文件...),space用来作vim的leader了...
> ...还有..用jk上下的是时候有1/3会触发两次(按一下j下移两行)
> 看代码好像jk的时候必须capslock和jk等键一起松才能立即停下? 但是里面有一些变量看名称不好猜作用, 求简单解释一下....
比如这里的mtl mtr mtu tda 之类........

虽然close了不过还是回一下好了，

1. capslock和space是默认（推荐space），此外还支持其它的几个比如ins和alt之类需要在设置 config.ini 里开，功能上没有差别。
2. 不推荐 win ctrl shift alt，因为很多键位冲突，比如Win+E资源管理器 Ctrl+A全选 Shift大写 等……想改的话可以考虑研究一下Help.ahk 然后自己写个 `win_as_clx.user.ahk` 放上去（`*.user.ahk` 不会被更新影响），反正只是调用一个 CapsLockX_Dn 和 CapsLockX_Up 这2个函数的事
3. 试试新版本？还会重复触发吗？
4. 是的，不过不放开CLX一般也就多滑一会……如果放开JK还一直滑的话，一定是BUG。
5. 变量名称在新版全部换成了中文，应该好理解得多。

**Comment by WillDawnlll** [comment]
感谢回复。。改成右alt了。。（用空格打字有点延迟，capslock和esc换了）。。变量名仔细看了一下api参数大概懂。。多次移动估计是因为加速度和用的conemu+far有点冲突，就把加速度删了。。但是语法又忘了用更新的还要再改。。再次感谢这个好用的工具拯救我的winds键盘体验。。

**Comment by snomiao** [comment]
新版空格打字做了点优化，现在只有单打空格键的时候会延迟，如果先按了别的键再按空格就还是原功能，例如输入法上屏，而且没有延迟，对打字影响已经非常非常小了~ 你可以试试新版本~

**Comment by WillDawnlll** [comment]
新版空格很好用, 只是我比较常用连按空格打空白, 所以还是用的右alt, 感谢可以ini配置
...只是jk还是会因为加速度, 出现连按3,4次, 移动两行, 改了ini里的加速度0就好了
...之前把左右键换了一下,差点以为是我又不会用了...
...长按功能键显示的快捷键页面前几个中文乱码了, 这时也不好截图.....

**Comment by snomiao** [comment]
1. 长按空格打空白的功能，在新版本 还原出来了~
1. JK在我这里没有出问题，可以提供一下出错的环境吗？或者测试一下别的电脑，也许是隐藏的 bug。
1. 左右键是指？
1. 乱码已修~

**Comment by WillDawnlll** [comment]
左右键是鼠标的...最开始那个版本换了一下...
jk : 我的环境是win1020h2 里的,  这是另一个win7中![t](https://user-images.githubusercontent.com/28567110/115500742-7ff48680-a2a4-11eb-81ae-d96f30a684c5.gif)
我这配置文件里光标加速度设为0可以解决, 如果你复现时不明显的话, 把加速的调高可能会出现?( 我连按的时候不松开功能键, 也许和这个有关系.....

**Comment by WillDawnlll** [comment]
对了...请问在vmware的ui里有方式使用吗, 从其他窗口移入时可用, 点击一次, vmware变主窗口后就失效了(不是在虚拟机的窗口中)......影响的原因有什么建议的关键词吗....没查到...是因为被虚拟机驱动拦截按键消息了吗....

**Comment by snomiao** [comment]
> 对了...请问在vmware的ui里有方式使用吗, 从其他窗口移入时可用, 点击一次, vmware变主窗口后就失效了(不是在虚拟机的窗口中)......影响的原因有什么建议的关键词吗....没查到...是因为被虚拟机驱动拦截按键消息了吗....

1. 一种可能是 ignores掉了，
可以检查一下 `User/CapsLockX.user.ignores.txt`。
（不过默认应该没有vmware...因为我平常用hyperv和virtualbox。）
2. 另一种可能就是capslockx管理员权限没开，而vmware是管理员权限的窗口，于是在它上面就有可能失效
3. 如果12都不是，那就只能想到被拦截了。。。（暂时无解）

**Comment by snomiao** [comment]
> 左右键是鼠标的...最开始那个版本换了一下...
> jk : 我的环境是win1020h2 里的, 这是另一个win7中![t](https://user-images.githubusercontent.com/28567110/115500742-7ff48680-a2a4-11eb-81ae-d96f30a684c5.gif)
> 我这配置文件里光标加速度设为0可以解决, 如果你复现时不明显的话, 把加速的调高可能会出现?( 我连按的时候不松开功能键, 也许和这个有关系.....

btw为啥你的录屏是黑白（灰度）的……

**Comment by WillDawnlll** [comment]
vmw不是12...gif是之前选的设置没改...
