### ISSUE TITLE
请问如何自定义按键？

### ISSUE THREAD

**Issue by Sander-Chen** [snolab/CapsLockX#70]
作者您好，非常感谢您开发的这款软件，我之前使用的是Capslock+，但它不再更新了，于是就找到您开发的这款Capslock+，我觉得功能非常丰富，软件稳定性也很好，目前就是有几个使用习惯的问题:
1. 如何编辑移动的键位呢？hjkl等
2. 是否可以支持选中，比如capslock+i等于选中向上一行字符等

期待作者的回复！

**Comment by snomiao** [comment]
1. fork到你的倉庫，在 modules裏面找CLX-Edit.ahk 最下面hjkl的定義
![image](https://user-images.githubusercontent.com/7323030/224855525-da9635a2-59b0-4c98-93a6-52556dde8b12.png)
改好然後重新運行

2. 按住 shfit 。比如 CLX+shift+i

**Comment by Sander-Chen** [comment]
> 1. fork到你的倉庫，在 modules裏面找CLX-Edit.ahk 最下面hjkl的定義
>    ![image](https://user-images.githubusercontent.com/7323030/224855525-da9635a2-59b0-4c98-93a6-52556dde8b12.png)
>    改好然後重新運行
> 2. 按住 shfit 。比如 CLX+shift+i

非常感谢您的答复！
