### ISSUE TITLE
增强鼠标功能

### ISSUE THREAD

**Issue by Kuwaaaa** [snolab/CapsLockX#77]
目前鼠标功能非常酷，但还有些不太好用的地方：
1. 鼠标初速度配置文件里好像调整不了，希望可以增加该配置
2. 鼠标速度没有上限，跨大区域时很难操控，建议增加一个速度上限
3. 目前鼠标只能沿一个方向移动， 希望可以该湖北
4. 将鼠标的这些配置分组，像是现代鼠标一样可以随时切换配置

**Comment by snomiao** [comment]
1. 速度可以调整，初速度是指更具体的参数吗？你可以去看看 AccModel.ahk 那个文件里研究下怎么改（不过注意hjkl光标也受影响）
2. 上限问题我可以考虑加一下……
3. 湖北？？鼠标方向是可以WA或者SD斜行走的，你说的是这个意思吗？如果是的话，一般能打游戏的键盘应该都支持。你可以换换键盘试试，如果不是这个意思的话请具体描述一下你希望可以……？
4. 分组功能工作量比较大，近期我本人应该没什么空……欢迎各位dalao出点魔改版
