### ISSUE TITLE
怎么把capslock改成双击是切换大小写？

### ISSUE THREAD

**Issue by stepdc** [snolab/CapsLockX#80]
超赞的项目，用起来很顺手，👍👍👍

手残党按组合键的时候，经常变成单击CapsLock，又不想映射成其他快捷键，有没有办法像标题一样双击切换大小写？

**Comment by snomiao** [comment]
小技巧：按完clx如果接键有犹豫的话，马上按一下wasd，可以规避弹起时识别成原按键的问题，对于 CapsLock + * 和 Space + * 都管用。

**Comment by snomiao** [comment]
或者想一直呆在CapsLockX模式里的话，按 CapsLock+空格键 就可以进入
