### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by lnfuhl** [snolab/CapsLockX#82]
Add a long press caps action to null, which reduces caps switching. The acceleration controlled by the mouse is a bit strange, and the backspace key is too inconvenient

**Comment by snomiao** [comment]
> Add a long press caps action to null, which reduces caps switching.

没懂……可以详细解释一下吗？长按caps目前的设计是如果不接clx热键就会使用capslock本来的功能。

> The acceleration controlled by the mouse is a bit strange

eh，加速模型可以在 AccModel， 如果你有手感比较好的算法可以发在这里给大家试试

> and the backspace key is too inconvenient

指按t=delete吗？可否说说哪不方便
