### ISSUE TITLE
自動更新的一點點想法

### ISSUE THREAD

**Issue by steveh8758** [snolab/CapsLockX#87]
最近我也有嘗試想要自動更新，不然太不方便了，我個人的做法是架一個 HFS 的伺服器，透過 CURL 去 upload ，加上壓縮檔的自解和執行指令，應該算是方便，供參。

下載也可以如是的方式去載

```cmd
REM make self unzip
%RAR_DIR% a -ep1 -r %RAR_OUTPUT_FILE_DIR% %FILE_DIR%.exe .\DelSelf.cmd -sfx -iicon%ICON_DIR% -z.\tmp.ini -p%RAR_PWD% -m5 -df

REM Upload AHKOOL_SETUP.exe to server
curl -u %HFS_ACC%:%HFS_PWD% -X POST -F "file=@%RAR_OUTPUT_FILE_DIR%" -F press="Upload files" %HFS_SERVER%
```

**Comment by snomiao** [comment]
你用的什麼安装方式？最近有遇到無法更新的問題嗎？

如果是包管理安装的話一般還是通過包管理工具来更新比較好。

如果是编携版的話，目前好像是手動更新，等我闲了再研究下。。

自解圧的方式很值得参考。

CURL upload応該用不上，因為github action会自動上伝到release裏面。

**Comment by steveh8758** [comment]
我用的是攜帶版的，因為有些時候會加入自己的功能，

所以才有上面的建議和用法，謝謝大佬！
