### ISSUE TITLE
请问怎么提取其中的鼠标模拟功能

### ISSUE THREAD

**Issue by 1205129045x** [snolab/CapsLockX#88]
我想设置成按d键然后再按hjkl模拟鼠标上下左右的，该怎么看源码自己改？

**Comment by snomiao** [comment]
如果是要把鼠標模擬拆出来的話，

1. 主要是拆出来这2個文件
.\Modules\AccModel\AccModel.ahk
.\Modules\CLX-Mouse.ahk

2. 把 CapsLockX_Config 換成你想要的值
3. 刪掉 CapsLockX_AppendHelp
4. 刪掉環境検査

```autohotkey
if (!CapsLockX) {
    MsgBox, % "本模块只为 CapsLockX 工作"
    ExitApp
}
```

5. 把 CapsLockXMode 替換成 HJKLMouseMode，然后把原有的熱鍵控制代碼換成你想要的様子，類似这样

```autohotkey

; 按d键进入鼠标模式

#if

*d::
    global HJKLMouseMode := 1
    return
*d Up::
    global HJKLMouseMode := 0
    return

; 在 hjkl鼠標模式下，按下hjkl鍵，模擬鼠標移動
#if HJKLMouseMode

; 鼠标运动处理
*h:: 鼠标模拟.左按("h")
*l:: 鼠标模拟.右按("l")
*k:: 鼠标模拟.上按("k")
*j:: 鼠标模拟.下按("j")

```

6. 可能存在的問題：
   1. d鍵作為触发鍵的話，可能影响輸入法。
   2. 以上示例未提供滚轮支持，也没提供鼠標点撃支持

@1205129045x  有思路了嗎

**Comment by 1205129045x** [comment]
> 如果是要把鼠標模擬拆出来的話，
> 
> 1. 主要是拆出来这2個文件
>    .\Modules\AccModel\AccModel.ahk
>    .\Modules\CLX-Mouse.ahk
> 2. 把 CapsLockX_Config 換成你想要的值
> 3. 刪掉 CapsLockX_AppendHelp
> 4. 刪掉環境検査
> 
> ```ahk
> if (!CapsLockX) {
>     MsgBox, % "本模块只为 CapsLockX 工作"
>     ExitApp
> }
> ```
> 
> 5. 把 CapsLockXMode 替換成 HJKLMouseMode，然后把原有的熱鍵控制代碼換成你想要的様子，類似这样
> 
> ```ahk
> ; 按d键进入鼠标模式
> 
> #if
> 
> *d::
>     global HJKLMouseMode := 1
>     return
> *d Up::
>     global HJKLMouseMode := 0
>     return
> 
> ; 在 hjkl鼠標模式下，按下hjkl鍵，模擬鼠標移動
> #if HJKLMouseMode
> 
> ; 鼠标运动处理
> *h:: 鼠标模拟.左按("h")
> *l:: 鼠标模拟.右按("l")
> *k:: 鼠标模拟.上按("k")
> *j:: 鼠标模拟.下按("j")
> ```
> 
> 6. 可能存在的問題：
>    
>    1. d鍵作為触发鍵的話，可能影响輸入法。
>    2. 以上示例未提供滚轮支持，也没提供鼠標点撃支持
> 
> @1205129045x 有思路了嗎

太强了 你是作者吧 有思路了 周末开搞

**Comment by snomiao** [comment]
> > 如果是要把鼠標模擬拆出来的話，
> > 
> > 1. 主要是拆出来这2個文件
> >    .\Modules\AccModel\AccModel.ahk
> >    .\Modules\CLX-Mouse.ahk
> > 2. 把 CapsLockX_Config 換成你想要的值
> > 3. 刪掉 CapsLockX_AppendHelp
> > 4. 刪掉環境検査
> > 
> > ```ahk
> > if (!CapsLockX) {
> >     MsgBox, % "本模块只为 CapsLockX 工作"
> >     ExitApp
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 5. 把 CapsLockXMode 替換成 HJKLMouseMode，然后把原有的熱鍵控制代碼換成你想要的様子，類似这样
> > 
> > ```ahk
> > ; 按d键进入鼠标模式
> > 
> > #if
> > 
> > *d::
> >     global HJKLMouseMode := 1
> >     return
> > *d Up::
> >     global HJKLMouseMode := 0
> >     return
> > 
> > ; 在 hjkl鼠標模式下，按下hjkl鍵，模擬鼠標移動
> > #if HJKLMouseMode
> > 
> > ; 鼠标运动处理
> > *h:: 鼠标模拟.左按("h")
> > *l:: 鼠标模拟.右按("l")
> > *k:: 鼠标模拟.上按("k")
> > *j:: 鼠标模拟.下按("j")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 6. 可能存在的問題：
> >    
> >    1. d鍵作為触发鍵的話，可能影响輸入法。
> >    2. 以上示例未提供滚轮支持，也没提供鼠標点撃支持
> > 
> > @1205129045x 有思路了嗎
> 
> 太强了 你是作者吧 有思路了 周末开搞

有進展吗 @1205129045x

**Comment by snomiao** [comment]
Some one done this, maybe its'you, how ever I archived into here

- [snomiao/snomouse-bak: Drafting]( https://github.com/snomiao/snomouse-bak )

**Comment by 11215548** [comment]
上周末花了两天才搞出来，可以实现按d进入鼠标模式，组合hjkl负责移动，但是并不影响快速输入一个d和长按d。
```ahk
#SingleInstance, Force
SetWorkingDir, %A_ScriptDir%
global MouseControlMode := false
global CapsLockXMode := true  ; 假设 CapsLockXMode 始终为真，您可以根据需要修改这个逻辑
global dKeyPressTime := 0
global dKeyHoldThreshold := 200  ; 长按阈值（毫秒）
global ReadyForMouseMode := false
$d::
    dKeyPressTime := A_TickCount
    MouseControlMode := true
    ReadyForMouseMode := true
    SetTimer, CheckHJKL, 10
    while (GetKeyState("d", "P"))
    {
        if (!ReadyForMouseMode && A_TickCount - dKeyPressTime > dKeyHoldThreshold)
        {
            if (!GetKeyState("h", "P") && !GetKeyState("j", "P") && !GetKeyState("k", "P") && !GetKeyState("l", "P"))
            {
                SendInput, {Blind}{d DownTemp}
                Sleep, 10
                SendInput, {Blind}{d Up}
            }
        }
        Sleep, 10
    }
    SetTimer, CheckHJKL, Off
    MouseControlMode := false
    ReadyForMouseMode := false
    if (A_TickCount - dKeyPressTime < dKeyHoldThreshold)
    {
        Send, d  ; 快速点击，输入 'd'
    }
return
CheckHJKL:
    if (ReadyForMouseMode && GetKeyState("d", "P") && (GetKeyState("h", "P") || GetKeyState("j", "P") || GetKeyState("k", "P") || GetKeyState("l", "P")))
    {
        MouseControlMode := false
        SetTimer, CheckHJKL, Off  ; 停止计时器，因为我们已经进入鼠标模式
    }
    if(A_TickCount - dKeyPressTime > 500 && MouseControlMode)
    {
        ReadyForMouseMode := false
        SetTimer, CheckHJKL, Off  ; 如果超过500ms没有进入鼠标模式，也停止计时器
    }
return
#if CapsLockXMode && ReadyForMouseMode
*h:: 鼠标模拟.左按("h")
*j:: 鼠标模拟.下按("j")
*k:: 鼠标模拟.上按("k")
*l:: 鼠标模拟.右按("l")
; 当释放 HJKL 键时停止移动
*h up:: 鼠标模拟.左弹("h")
*j up:: 鼠标模拟.下弹("j")
*k up:: 鼠标模拟.上弹("k")
*l up:: 鼠标模拟.右弹("l")
```
大佬你是怎么判断单按一下大写键是正常的大写。
接下来打算是按住d和s不放松，再按j或k实现上滚和下滚功能。
解放小拇指，不按大写键。

**Comment by snomiao** [comment]
> 判断单按一下大写键是正常的大写。

- 按下大写键之后，没跟其它键就弹起 = 正常大写
- 按下大写键之后，跟了其它热键 = 走具体热键的功能

@11215548

**Comment by 11215548** [comment]
我现在发现按d会有延迟，比如打`的`这个字，我一般输入法都会按下d再按空格，按的比较快，空格就会先触发了，是不是程序有延迟

**Comment by snomiao** [comment]
用来做触发键的肯定会有延迟的，用d的话打d会延迟，用空格的话打空格会延迟

我个人觉得空格延迟比较可以接受

**Comment by 11215548** [comment]
> 用来做触发键的肯定会有延迟的，用d的话打d会延迟，用空格的话打空格会延迟
> 
> 我个人觉得空格延迟比较可以接受

指的是用空格做触发键吗，有办法改代码让延迟不影响我快速打字吗

**Comment by snomiao** [comment]
具体来说，你在什么环节有延迟？

case1 使用clx, 按空格+热键
0ms 按下空格
100ms 按下热键 wasd
200ms 弹起空格

case2 使用clx，按空格，输出空格
0ms 按下空格
100ms 弹起空格（输出空格）

case3 不使用clx，输出空格
0ms 按下空格(输出空格)

如果你想打空格的话，case2相比case3多了100ms延迟
但为了让case1正常运行，空格不能直接在按下时立刻输出，目前CLX在这个情况使用了250ms延迟，打空格如果 不使用热键，会延迟250ms才输出空格，此时保持空格按下可连续输出空格。

相关代码见此
https://github.com/snomiao/capslockx/blob/71aadc2c23aee35d1b0745e5b5a0300309338bdc/Core/CapslockX-Core.ahk#L322C35-L340C10

**Comment by snomiao** [comment]
关于打字，你可以使用不影响打字的引导键，比如右alt或capslock这些平时打字 不会用到的键做引导键，就不会导致打字延迟了

**Comment by 11215548** [comment]
我现在的代码是。
```
$d::
    dKeyPressTime := A_TickCount
    while (GetKeyState("d", "P"))
    {
        //检测是否长按的
    }
    SetTimer, CheckHJKL, 10 //具体判断是否进入鼠标模式的代码。
    if (A_TickCount - dKeyPressTime < dKeyHoldThreshold)
    {
        Send, d  ; 快速点击，输入 'd'
    }
return
```
因为有这个`while (GetKeyState("d", "P"))`，只有当d键弹开了，才会输入d，所以有延迟，但是又没法删掉，因为要检测是否会进入鼠标模式。
所以case情况是：
case1:单独按一下d
0ms 按下d
d键弹起，才会输入d

case2 长按d
会根据while重复输入d

case3 d和其他键连着按
都会出现其他键先被按出来，d才会被按出来，应该就是前面的while循环导致的。只有d弹起了，d才会输入。

**Comment by snomiao** [comment]
这样的話我建議你使用不影响打字的引导键，比如右alt或capslock这些平时打字 不会用到的键做引导键，就不会导致打字延迟了

**Comment by 11215548** [comment]
> 这样的話我建議你使用不影响打字的引导键，比如右alt或capslock这些平时打字 不会用到的键做引导键，就不会导致打字延迟了

可以。老老实实用右alt或ctrl了。
