### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by Alexnoj** [snolab/CapsLockX#91]
Can you make full english version?

Thanks.

**Comment by snomiao** [comment]
thank you for request！I ll try to make user interface readable in english
in next，Do you need english translate of ahk code too？

**Comment by snomiao** [comment]
btw could u share me where do you find capslockx？

**Comment by Alexnoj** [comment]
> btw could u share me where do you find capslockx？

In Google. I searched AHK scrips.

> thank you for request！I ll try to make user interface readable in english
> in next，Do you need english translate of ahk code too？

At start just user interface, at next if u will have time ahk code too.

Thanks

**Comment by snomiao** [comment]
not stale

**Comment by snomiao** [comment]
not stale

**Comment by snomiao** [comment]
![image](https://github.com/snolab/CapsLockX/assets/7323030/b5a898bc-b6f8-47cc-bddb-4795adad7a05)

**Comment by snomiao** [comment]
![image](https://github.com/snolab/CapsLockX/assets/7323030/1e4af340-78af-43b9-9acd-1effeca4112c)

Now CLX Interfaces is auto translated into users language on the fly.
