### ISSUE TITLE
windows11  capslock+shift  3  时应用会切换到桌面2 二不是桌面3  

### ISSUE THREAD

**Issue by zanone** [snolab/CapsLockX#93]
windows11  capslock+shift  3  时应用会切换到桌面2 二不是桌面3  
 在桌面1 按capslock  3 会先过桌面2 在到桌面3

**Comment by snomiao** [comment]
問題原因：win11下無法正常調用虚擬桌面api，於是使用了fallback 热键切換

TODO：楼主有無興趣幫忙調査一下 win11下新版虚擬桌面 api 接口是哪個 @zanone

**Comment by snomiao** [comment]
done with
; 2024-05-19 - [VirtualDesktop/VirtualDesktop11.cs at master · MScholtes/VirtualDesktop]( https://github.com/MScholtes/VirtualDesktop/blob/master/VirtualDesktop11.cs )
